# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Description of what the lane does"
  lane :beta do
    appcenter_upload(
      api_token: "069fb43c4d645650ce7ed03ec0900f9aee88629c",
      owner_name: "afzalive",
      owner_type: "user",
      app_name: "Mailgun-Routes-Mac",
      app_platform: "mac",
      ipa: "../build/macos/Build/Products/Release/mailgun_routes.app",
      notify_testers: true
    )
  end
end
