# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

lane :beta do |options|

    ios(options)
    android(options)
    mac(options)

end

lane :ios do |options|

    Dir.chdir("..") do
        sh("flutter", "build", "ios")
    end

    Dir.chdir("../build/ios/iphoneos") do
        sh("mkdir", "Payload")
        sh("cp", "-r", "Mailgun\ Routes.app", "Payload/")
        sh("zip", "--symlinks", "-qr", "Runner.ipa", "Payload")
    end

 #  Creates a smaller IPA but rebuilds the whole app!
 #  If enabled, remember to change the file path in
 #  appcenter_upload to build/ios/iphoneos/MailgunRoutes
 #
 #   build_ios_app(
 #       workspace: "ios/Runner.xcworkspace",
 #       export_options: "ios/exportOptions.plist",
 #       output_directory: "build/ios/iphoneos/MailgunRoutes",
 #       output_name: "Runner.ipa"
 #   )

    appcenter_upload(
        api_token: options[:api_token],
        owner_name: "afzalive",
        owner_type: "user",
        app_name: "Mailgun-Routes-iOS",
        app_platform: "ios",
        file: "build/ios/iphoneos/Runner.ipa",
        notify_testers: true
    )

end

lane :android do |options|

    Dir.chdir("..") do
        sh("flutter", "build", "apk")
    end

    appcenter_upload(
        api_token: options[:api_token],
        owner_name: "afzalive",
        owner_type: "user",
        app_name: "Mailgun-Routes",
        app_os: 'Android',
        file: "build/app/outputs/apk/release/app-release.apk",
        notify_testers: true
    )

end

lane :mac do |options|

    Dir.chdir("..") do
        sh("flutter", "build", "macos")
    end

    appcenter_upload(
        api_token: options[:api_token],
        owner_name: "afzalive",
        owner_type: "user",
        app_name: "Mailgun-Routes-Mac",
        app_platform: "mac",
        file: "build/macos/Build/Products/Release/Mailgun Routes.app",
        notify_testers: true
    )

end


