# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

lane :beta do |options|

    android
    ios
    mac

end

lane :ios do |options|

    build_ios_app(
        workspace: "ios/Runner.xcworkspace",
        export_options: "ios/exportOptions.plist",
        output_directory: "build/ios/iphoneos/MailgunRoutes",
        output_name: "Runner.ipa"
    )

    appcenter_upload(
        api_token: options[:api_token],
        owner_name: "afzalive",
        owner_type: "user",
        app_name: "Mailgun-Routes-iOS",
        app_platform: "ios",
        file: "build/ios/iphoneos/MailgunRoutes/Runner.ipa",
        notify_testers: true
    )

end

lane :android do |options|

    appcenter_upload(
        api_token: options[:api_token],
        owner_name: "afzalive",
        owner_type: "user",
        app_name: "Mailgun-Routes",
        app_os: 'Android',
        file: "build/app/outputs/apk/release/app-release.apk",
        notify_testers: true
    )


end

lane :mac do |options|

    appcenter_upload(
        api_token: options[:api_token],
        owner_name: "afzalive",
        owner_type: "user",
        app_name: "Mailgun-Routes-Mac",
        app_platform: "mac",
        file: "build/macos/Build/Products/Release/Mailgun Routes.app",
        notify_testers: true
    )

end


