# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do |options|
  # increment_build_number

  # build your iOS app
  # build_app(
    # scheme: "YourScheme",
    #export_method: "ad-hoc"
  #)

  # upload to Beta by Crashlytics
  #crashlytics(
  #  api_token: options[:api_token],
  #  build_secret: options[:build_secret],
  #)

  appcenter_upload(
    api_token: "069fb43c4d645650ce7ed03ec0900f9aee88629c",
    owner_name: "afzalive",
    owner_type: "user",
    app_name: "Mailgun-Routes-iOS",
    app_platform: "ios",
    ipa: "../build/ios/iphoneos/MailgunRoutes/Runner.ipa",
    notify_testers: true
  )
end
