# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do |options|
  # build the release variant
  # build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  # crashlytics(
  #  api_token: options[:api_token],
  #  build_secret: options[:build_secret],
  #  apk_path: "../build/app/outputs/apk/release/app-release.apk",
  #  groups: "all"
  #)

  appcenter_upload(
    api_token: "069fb43c4d645650ce7ed03ec0900f9aee88629c",
    owner_name: "afzalive",
    owner_type: "user",
    app_name: "Mailgun-Routes",
    app_os: 'Android',
    file: "../build/app/outputs/apk/release/app-release.apk",
    notify_testers: true
  )
end
